return {
    [0] = { name = "unknown" },
    [1] = { name = "Phanauet Channel" },
    [2] = { name = "Carpenters' Landing" },
    [3] = { name = "Manaclipper" },
    [4] = { name = "Bibiki Bay" },
    [5] = { name = "Uleguerand Range" },
    [6] = { name = "Bearclaw Pinnacle" },
    [7] = { name = "Attohwa Chasm" },
    [8] = { name = "Boneyard Gully" },
    [9] = { name = "Pso'Xja" },
    [10] = { name = "The Shrouded Maw" },
    [11] = { name = "Oldton Movalpolos" },
    [12] = { name = "Newton Movalpolos" },
    [13] = { name = "Mine Shaft #2716" },
    [14] = { name = "Hall of Transference" },
    [15] = { name = "Abyssea - Konschtat" },
    [16] = { name = "Promyvion - Holla" },
    [17] = { name = "Spire of Holla" },
    [18] = { name = "Promyvion - Dem" },
    [19] = { name = "Spire of Dem" },
    [20] = { name = "Promyvion - Mea" },
    [21] = { name = "Spire of Mea" },
    [22] = { name = "Promyvion - Vahzl" },
    [23] = { name = "Spire of Vahzl" },
    [24] = { name = "Lufaise Meadows" },
    [25] = { name = "Misareaux Coast" },
    [26] = { name = "Tavnazian Safehold" },
    [27] = { name = "Phomiuna Aqueducts" },
    [28] = { name = "Sacrarium" },
    [29] = { name = "Riverne - Site #B01" },
    [30] = { name = "Riverne - Site #A01" },
    [31] = { name = "Monarch Linn" },
    [32] = { name = "Sealion's Den" },
    [33] = { name = "Al'Taieu" },
    [34] = { name = "Grand Palace of Hu'Xzoi" },
    [35] = { name = "The Garden of Ru'Hmet" },
    [36] = { name = "Empyreal Paradox" },
    [37] = { name = "Temenos" },
    [38] = { name = "Apollyon" },
    [39] = { name = "Dynamis - Valkurm" },
    [40] = { name = "Dynamis - Buburimu" },
    [41] = { name = "Dynamis - Qufim" },
    [42] = { name = "Dynamis - Tavnazia" },
    [43] = { name = "Diorama Abdhaljs-Ghelsba" },
    [44] = { name = "Abdhaljs Isle-Purgonorgo" },
    [45] = { name = "Abyssea - Tahrongi" },
    [46] = { name = "Open sea route to Al Zahbi" },
    [47] = { name = "Open sea route to Mhaura" },
    [48] = { name = "Al Zahbi" },
    [49] = { name = "none" },
    [50] = { name = "Aht Urhgan Whitegate" },
    [51] = { name = "Wajaom Woodlands" },
    [52] = { name = "Bhaflau Thickets" },
    [53] = { name = "Nashmau" },
    [54] = { name = "Arrapago Reef" },
    [55] = { name = "Ilrusi Atoll" },
    [56] = { name = "Periqia" },
    [57] = { name = "Talacca Cove" },
    [58] = { name = "Silver Sea route to Nashmau" },
    [59] = { name = "Silver Sea route to Al Zahbi" },
    [60] = { name = "The Ashu Talif" },
    [61] = { name = "Mount Zhayolm" },
    [62] = { name = "Halvung" },
    [63] = { name = "Lebros Cavern" },
    [64] = { name = "Navukgo Execution Chamber" },
    [65] = { name = "Mamook" },
    [66] = { name = "Mamool Ja Training Grounds" },
    [67] = { name = "Jade Sepulcher" },
    [68] = { name = "Aydeewa Subterrane" },
    [69] = { name = "Leujaoam Sanctum" },
    [70] = { name = "Chocobo Circuit" },
    [71] = { name = "The Colosseum" },
    [72] = { name = "Alzadaal Undersea Ruins" },
    [73] = { name = "Zhayolm Remnants" },
    [74] = { name = "Arrapago Remnants" },
    [75] = { name = "Bhaflau Remnants" },
    [76] = { name = "Silver Sea Remnants" },
    [77] = { name = "Nyzul Isle" },
    [78] = { name = "Hazhalm Testing Grounds" },
    [79] = { name = "Caedarva Mire" },
    [80] = { name = "Southern San d'Oria [S]" },
    [81] = { name = "East Ronfaure [S]" },
    [82] = { name = "Jugner Forest [S]" },
    [83] = { name = "Vunkerl Inlet [S]" },
    [84] = { name = "Batallia Downs [S]" },
    [85] = { name = "La Vaule [S]" },
    [86] = { name = "Everbloom Hollow" },
    [87] = { name = "Bastok Markets [S]" },
    [88] = { name = "North Gustaberg [S]" },
    [89] = { name = "Grauberg [S]" },
    [90] = { name = "Pashhow Marshlands [S]" },
    [91] = { name = "Rolanberry Fields [S]" },
    [92] = { name = "Beadeaux [S]" },
    [93] = { name = "Ruhotz Silvermines" },
    [94] = { name = "Windurst Waters [S]" },
    [95] = { name = "West Sarutabaruta [S]" },
    [96] = { name = "Fort Karugo-Narugo [S]" },
    [97] = { name = "Meriphataud Mountains [S]" },
    [98] = { name = "Sauromugue Champaign [S]" },
    [99] = { name = "Castle Oztroja [S]" },
    [100] = { name = "West Ronfaure" },
    [101] = { name = "East Ronfaure" },
    [102] = { name = "La Theine Plateau" },
    [103] = { name = "Valkurm Dunes" },
    [104] = { name = "Jugner Forest" },
    [105] = { name = "Batallia Downs" },
    [106] = { name = "North Gustaberg" },
    [107] = { name = "South Gustaberg" },
    [108] = { name = "Konschtat Highlands" },
    [109] = { name = "Pashhow Marshlands" },
    [110] = { name = "Rolanberry Fields" },
    [111] = { name = "Beaucedine Glacier" },
    [112] = { name = "Xarcabard" },
    [113] = { name = "Cape Teriggan" },
    [114] = { name = "Eastern Altepa Desert" },
    [115] = { name = "West Sarutabaruta" },
    [116] = { name = "East Sarutabaruta" },
    [117] = { name = "Tahrongi Canyon" },
    [118] = { name = "Buburimu Peninsula" },
    [119] = { name = "Meriphataud Mountains" },
    [120] = { name = "Sauromugue Champaign" },
    [121] = { name = "The Sanctuary of Zi'Tah" },
    [122] = { name = "Ro'Maeve" },
    [123] = { name = "Yuhtunga Jungle" },
    [124] = { name = "Yhoator Jungle" },
    [125] = { name = "Western Altepa Desert" },
    [126] = { name = "Qufim Island" },
    [127] = { name = "Behemoth's Dominion" },
    [128] = { name = "Valley of Sorrows" },
    [129] = { name = "Ghoyu's Reverie" },
    [130] = { name = "Ru'Aun Gardens" },
    [131] = { name = "Mordion Gaol" },
    [132] = { name = "Abyssea - La Theine" },
    [133] = { name = "Cape Teriggan" },
    [134] = { name = "Dynamis - Beaucedine" },
    [135] = { name = "Dynamis - Xarcabard" },
    [136] = { name = "Beaucedine Glacier [S]" },
    [137] = { name = "Xarcabard [S]" },
    [138] = { name = "Castle Zvahl Baileys [S]" },
    [139] = { name = "Horlais Peak" },
    [140] = { name = "Ghelsba Outpost" },
    [141] = { name = "Fort Ghelsba" },
    [142] = { name = "Yughott Grotto" },
    [143] = { name = "Palborough Mines" },
    [144] = { name = "Waughroon Shrine" },
    [145] = { name = "Giddeus" },
    [146] = { name = "Balga's Dais" },
    [147] = { name = "Beadeaux" },
    [148] = { name = "Qulun Dome" },
    [149] = { name = "Davoi" },
    [150] = { name = "Monastic Cavern" },
    [151] = { name = "Castle Oztroja" },
    [152] = { name = "Altar Room" },
    [153] = { name = "The Boyahda Tree" },
    [154] = { name = "Dragon's Aery" },
    [155] = { name = "Castle Zvahl Keep [S]" },
    [156] = { name = "Throne Room [S]" },
    [157] = { name = "Middle Delkfutt's Tower" },
    [158] = { name = "Upper Delkfutt's Tower" },
    [159] = { name = "Temple of Uggalepih" },
    [160] = { name = "Den of Rancor" },
    [161] = { name = "Castle Zvahl Baileys" },
    [162] = { name = "Castle Zvahl Keep" },
    [163] = { name = "Sacrificial Chamber" },
    [164] = { name = "Garlaige Citadel [S]" },
    [165] = { name = "Throne Room" },
    [166] = { name = "Ranguemont Pass" },
    [167] = { name = "Bostaunieux Oubliette" },
    [168] = { name = "Chamber of Oracles" },
    [169] = { name = "Toraimarai Canal" },
    [170] = { name = "Full Moon Fountain" },
    [171] = { name = "Crawlers' Nest [S]" },
    [172] = { name = "Zeruhn Mines" },
    [173] = { name = "Korroloka Tunnel" },
    [174] = { name = "Kuftal Tunnel" },
    [175] = { name = "The Eldieme Necropolis [S]" },
    [176] = { name = "Sea Serpent Grotto" },
    [177] = { name = "Ve'Lugannon Palace" },
    [178] = { name = "The Shrine of Ru'Avitau" },
    [179] = { name = "Stellar Fulcrum" },
    [180] = { name = "La'Loff Amphitheater" },
    [181] = { name = "The Celestial Nexus" },
    [182] = { name = "Walk of Echoes" },
    [183] = { name = "Maquette Abdhaljs-Legion" },
    [184] = { name = "Lower Delkfutt's Tower" },
    [185] = { name = "Dynamis - San d'Oria" },
    [186] = { name = "Dynamis - Bastok" },
    [187] = { name = "Dynamis - Windurst" },
    [188] = { name = "Dynamis - Jeuno" },
    [189] = { name = "" },
    [190] = { name = "King Ranperre's Tomb" },
    [191] = { name = "Dangruf Wadi" },
    [192] = { name = "Inner Horutoto Ruins" },
    [193] = { name = "Ordelle's Caves" },
    [194] = { name = "Outer Horutoto Ruins" },
    [195] = { name = "The Eldieme Necropolis" },
    [196] = { name = "Gusgen Mines" },
    [197] = { name = "Crawlers' Nest" },
    [198] = { name = "Maze of Shakhrami" },
    [199] = { name = "" },
    [200] = { name = "Garlaige Citadel" },
    [201] = { name = "Cloister of Gales" },
    [202] = { name = "Cloister of Storms" },
    [203] = { name = "Cloister of Frost" },
    [204] = { name = "Fei'Yin" },
    [205] = { name = "Ifrit's Cauldron" },
    [206] = { name = "Qu'Bia Arena" },
    [207] = { name = "Cloister of Flames" },
    [208] = { name = "Quicksand Caves" },
    [209] = { name = "Cloister of Tremors" },
    [210] = { name = "" },
    [211] = { name = "Cloister of Tides" },
    [212] = { name = "Gustav Tunnel" },
    [213] = { name = "Labyrinth of Onzozo" },
    [214] = { name = "" },
    [215] = { name = "Abyssea - Attohwa" },
    [216] = { name = "Abyssea - Misareaux" },
    [217] = { name = "Abyssea - Vunkerl" },
    [218] = { name = "Abyssea - Altepa" },
    [219] = { name = "" },
    [220] = { name = "Ship bound for Selbina" },
    [221] = { name = "Ship bound for Mhaura" },
    [222] = { name = "Provenance" },
    [223] = { name = "San d'Oria-Jeuno Airship" },
    [224] = { name = "Bastok-Jeuno Airship" },
    [225] = { name = "Windurst-Jeuno Airship" },
    [226] = { name = "Kazham-Jeuno Airship" },
    [227] = { name = "Ship bound for Selbina" },
    [228] = { name = "Ship bound for Mhaura" },
    [229] = { name = "" },
    [230] = { name = "Southern San d'Oria" },
    [231] = { name = "Northern San d'Oria" },
    [232] = { name = "Port San d'Oria" },
    [233] = { name = "Chateau d'Oraguille" },
    [234] = { name = "Bastok Mines" },
    [235] = { name = "Bastok Markets" },
    [236] = { name = "Port Bastok" },
    [237] = { name = "Metalworks" },
    [238] = { name = "Windurst Waters" },
    [239] = { name = "Windurst Walls" },
    [240] = { name = "Port Windurst" },
    [241] = { name = "Windurst Woods" },
    [242] = { name = "Heavens Tower" },
    [243] = { name = "Ru'Lude Gardens" },
    [244] = { name = "Upper Jeuno" },
    [245] = { name = "Lower Jeuno" },
    [246] = { name = "Port Jeuno" },
    [247] = { name = "Rabao" },
    [248] = { name = "Selbina" },
    [249] = { name = "Mhaura" },
    [250] = { name = "Kazham" },
    [251] = { name = "Hall of the Gods" },
    [252] = { name = "Norg" },
    [253] = { name = "Abyssea - Uleguerand"},
    [254] = { name = "Abyssea - Grauberg" },
    [255] = { name = "Abyssea - Empyreal Paradox" },
    [256] = { name = "Western Adoulin" },
    [257] = { name = "Eastern Adoulin" },
    [258] = { name = "Rala Waterways" },
    [259] = { name = "Rala Waterways [U]" },
    [260] = { name = "Yahse Hunting Grounds" },
    [261] = { name = "Ceizak Battlegrounds" },
    [262] = { name = "Foret de Hennetiel" },
    [263] = { name = "Yorcia Weald" },
    [264] = { name = "Yorcia Weald [U]" },
    [265] = { name = "Morimar Basalt Fields" },
    [266] = { name = "Marjami Ravine" },
    [267] = { name = "Kamihr Drifts" },
    [268] = { name = "Sih Gates" },
    [269] = { name = "Moh Gates" },
    [270] = { name = "Cirdas Caverns" },
    [271] = { name = "Cirdas Caverns [U]" },
    [272] = { name = "Dho Gates" },
    [273] = { name = "Woh Gates" },
    [274] = { name = "Outer Ra'Kaznar" },
    [275] = { name = "Outer Ra'Kaznar [U]" },
    [276] = { name = "Ra'Kaznar Inner Court" },
    [277] = { name = "Ra'Kaznar Turris" },
    [278] = { name = "" },
    [279] = { name = "" },
    [280] = { name = "Mog Garden" },
    [281] = { name = "Leafallia" },
    [282] = { name = "Mount Kamihr" },
    [283] = { name = "Silver Knife" },
    [284] = { name = "Celennia Memorial Library" },
    [285] = { name = "Feretory" },
    [288] = { name = "Escha - Zi'Tah" },
    [289] = { name = "Escha - Ru'Aun" },
    [290] = { name = "Desuetia - Empyreal Paradox" },
    [291] = { name = "Reisenjima" },
    [292] = { name = "Reisenjima Henge" },
    [293] = { name = "Reisenjima Sanctorium" },
    [294] = { name = "Dynamis - San d'Oria [D]" },
    [295] = { name = "Dynamis - Bastok [D]" },
    [296] = { name = "Dynamis - Windurst [D]" },
    [297] = { name = "Dynamis - Jeuno [D]" }
}